[workspace]
resolver = "2"
members = [
    "forge-m365-macros",
    "forge-m365-core",
    "forge-m365-auth",
    "forge-m365-sp-sites",
    "forge-m365-sp-webs",
    "forge-m365-sp-lists",
    "forge-m365-sp-files",
    "forge-m365-sp-search",
    "forge-m365-sp-site-users",
    "forge-m365-sp-folders",
    "forge-m365-sp-content-types",
    "forge-m365-sp-site-groups",
    "forge-m365-sp-views",
    "forge-m365-sp-security",
    "forge-m365-sp-attachments",
    "forge-m365-sp-hubsites",
    "forge-m365",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/mentenaz/Forge.Microsoft.Rust.SDK"
authors = ["Mentenaz"]

[workspace.dependencies]
inventory = "0.3"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "blocking"] }
open = "5"
thiserror = "2"
base64 = "0.22"
percent-encoding = "2"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
rsa = { version = "0.9", features = ["sha2"] }

[profile.release]
lto = true
strip = true
